import csv

data = [
    ["University", "Location", "Rank", "Tuition Fee", "Start Month", "IELTS Requirement", "TOEFL Requirement", "Postgraduate Tuition Fee", "Postgraduate IELTS Requirement", "Postgraduate TOEFL Requirement", "Postgraduate Available", "Agent", "Undergraduate Programs", "Postgraduate Programs"],
    ["University of Auckland", "Auckland", 1, 22000, "February", 150, 85, 44000, 7, 65, "Yes", "Agent EE", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Engineering; Bachelor of Science", "Master of Business Administration; Master of Engineering; Master of Public Health; Master of Information Technology"],
    ["University of Otago", "Dunedin", 2, 20000, "February", 140, 80, 42000, 6.5, 60, "Yes", "Agent FF", "Bachelor of Medicine; Bachelor of Surgery; Bachelor of Dental Surgery; Bachelor of Laws", "Master of Business Administration; Master of Clinical Education; Master of Public Health; Master of Tourism"],
    ["Victoria University of Wellington", "Wellington", 3, 21000, "February", 130, 75, 40000, 6.5, 58, "Yes", "Agent GG", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["University of Canterbury", "Christchurch", 4, 20000, "February", 120, 70, 38000, 6.5, 58, "Yes", "Agent HH", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Massey University", "Palmerston North", 5, 19000, "February", 110, 65, 36000, 6.5, 58, "Yes", "Agent II", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["University of Waikato", "Hamilton", 6, 18000, "February", 100, 60, 34000, 6.5, 58, "Yes", "Agent JJ", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Auckland University of Technology", "Auckland", 7, 19000, "February", 105, 65, 37000, 6.5, 58, "Yes", "Agent KK", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Lincoln University", "Lincoln", 8, 18000, "February", 95, 55, 32000, 6.5, 58, "Yes", "Agent LL", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["University of Canterbury", "Christchurch", 4, 20000, "February", 120, 70, 38000, 6.5, 58, "Yes", "Agent MM", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Massey University", "Palmerston North", 5, 19000, "February", 110, 65, 36000, 6.5, 58, "Yes", "Agent NN", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["University of Waikato", "Hamilton", 6, 18000, "February", 100, 60, 34000, 6.5, 58, "Yes", "Agent OO", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Auckland University of Technology", "Auckland", 7, 19000, "February", 105, 65, 37000, 6.5, 58, "Yes", "Agent PP", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Lincoln University", "Lincoln", 8, 18000, "February", 95, 55, 32000, 6.5, 58, "Yes", "Agent QQ", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["University of Canterbury", "Christchurch", 4, 20000, "February", 120, 70, 38000, 6.5, 58, "Yes", "Agent RR", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Massey University", "Palmerston North", 5, 19000, "February", 110, 65, 36000, 6.5, 58, "Yes", "Agent SS", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["University of Waikato", "Hamilton", 6, 18000, "February", 100, 60, 34000, 6.5, 58, "Yes", "Agent TT", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Auckland University of Technology", "Auckland", 7, 19000, "February", 105, 65, 37000, 6.5, 58, "Yes", "Agent UU", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Lincoln University", "Lincoln", 8, 18000, "February", 95, 55, 32000, 6.5, 58, "Yes", "Agent VV", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["University of Canterbury", "Christchurch", 4, 20000, "February", 120, 70, 38000, 6.5, 58, "Yes", "Agent WW", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science", ""]
]
data += [
    ["University of Waikato", "Tauranga", 9, 18500, "February", 100, 60, 34500, 6.5, 58, "Yes", "Agent XX", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Eastern Institute of Technology", "Napier", 10, 17000, "February", 95, 55, 33000, 6.5, 58, "Yes", "Agent YY", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Nelson Marlborough Institute of Technology", "Nelson", 11, 16500, "February", 90, 50, 31000, 6.5, 58, "Yes", "Agent ZZ", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Southern Institute of Technology", "Invercargill", 12, 16000, "February", 85, 50, 30000, 6.5, 58, "Yes", "Agent AAA", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["NorthTec", "Whangarei", 13, 15500, "February", 80, 50, 29000, 6.5, 58, "Yes", "Agent BBB", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Waiariki Institute of Technology", "Rotorua", 14, 16000, "February", 85, 50, 29500, 6.5, 58, "Yes", "Agent CCC", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Whitireia Community Polytechnic", "Porirua", 15, 16500, "February", 90, 55, 31000, 6.5, 58, "Yes", "Agent DDD", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Bay of Plenty Polytechnic", "Tauranga", 16, 17000, "February", 95, 55, 32500, 6.5, 58, "Yes", "Agent EEE", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Western Institute of Technology at Taranaki", "New Plymouth", 17, 17500, "February", 100, 55, 33000, 6.5, 58, "Yes", "Agent FFF", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Tai Poutini Polytechnic", "Greymouth", 18, 18000, "February", 105, 60, 34000, 6.5, 58, "Yes", "Agent GGG", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Aoraki Polytechnic", "Timaru", 19, 18500, "February", 110, 60, 34500, 6.5, 58, "Yes", "Agent HHH", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Manukau Institute of Technology", "Auckland", 20, 19000, "February", 115, 65, 35000, 6.5, 58, "Yes", "Agent III", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Unitec New Zealand", "Auckland", 21, 19500, "February", 120, 70, 35500, 6.5, 58, "Yes", "Agent JJJ", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Otago Polytechnic", "Dunedin", 22, 20000, "February", 125, 70, 36000, 6.5, 58, "Yes", "Agent KKK", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Wellington Institute of Technology", "Wellington", 23, 20500, "February", 130, 75, 36500, 6.5, 58, "Yes", "Agent LLL", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Christchurch Polytechnic Institute of Technology", "Christchurch", 24, 21000, "February", 135, 75, 37000, 6.5, 58, "Yes", "Agent MMM", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Eastern Institute of Technology", "Auckland", 25, 21500, "February", 140, 80, 37500, 6.5, 58, "Yes", "Agent NNN", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Universal College of Learning", "Palmerston North", 26, 22000, "February", 145, 80, 38000, 6.5, 58, "Yes", "Agent OOO", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Bay of Plenty Polytechnic", "Rotorua", 27, 22500, "February", 150, 85, 38500, 6.5, 58, "Yes", "Agent PPP", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Northland Polytechnic", "Whangarei", 28, 23000, "February", 155, 85, 39000, 6.5, 58, "Yes", "Agent QQQ", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Eastern Institute of Technology", "Hastings", 29, 23500, "February", 160, 90, 39500, 6.5, 58, "Yes", "Agent RRR", "Bachelor of Arts; Bachelor of Commerce; Bachelor of Science; Bachelor of Engineering", "Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"],
    ["Auckland Institute of Studies", "Auckland", 30, 24000, "February", 165, 90, 40000, 6.5, 58, "Yes", "Agent SSS", "Bachelor of Arts; Bachelor of Business; Bachelor of Science; Bachelor of Engineering","Master of Business Administration; Master of Engineering; Master of Public Policy; Master of International Relations"]
]


# Define the file name
file_name = "new_zealand_universityy_data.csv"

# Write data to CSV file
with open(file_name, 'w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    # Write the header
    # writer.writerow(["Name", "Location", "Ranking", "Cost of Living", "Intakes", "Application Fees", "Under Graduate GPA/Percentage", "Under Graduate Tuition Fees", "IELTS marks required", "PTE marks required", "Gap?", "Post Graduate Tuition Fees", "Post Graduate GPA/Percentage", "Post Graduate IELTS", "Post Graduate PTE", "Post Graduate Gap Acceptance", "Agent", "Sample Undergraduate Courses", "Sample Postgraduate Courses"])
    # Write the data
    writer.writerows(data)

print("CSV file created successfully!")
